disabled_rules: # rule identifiers turned on by default to exclude from running
  - force_cast
  - force_try
  - line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods