name: Arkulator

options:
  bundleIdPrefix: com.urielh
  xcodeVersion: 15.0.1
  deploymentTarget:
    iOS: "17.0"
  useTabs: false
  postGenCommand: "open Arkulator.xcodeproj"

settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 5P4JJDT7CR
    MARKETING_VERSION: "1.6.0"
    BUNDLE_VERSION: "1"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0
#    SWIFT_STRICT_CONCURRENCY: "complete"

packages:
  RealmSwift:
    url: https://github.com/realm/realm-swift
    version: 10.49.0

targets:
  Arkulator:
    settings:
      TARGETED_DEVICE_FAMILY: 1
      SUPPORTS_MACCATALYST: false
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    platform: iOS
    type: application
    sources:
      - Arkulator
    scheme:
      testTargets:
        - ArkulatorTests
      gatherCoverageData: true
      coverageTargets:
        - Arkulator
    postCompileScripts:
      - script: |
          export PATH="$PATH:/opt/homebrew/bin"

          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi

        name: Swiftlint
    info:
      path: Arkulator/SupportingFiles/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIUserInterfaceStyle: Light
    entitlements:
      path: Arkulator/Arkulator.entitlements
      properties:
        com.apple.security.application-groups: [group.com.arkulator]
    dependencies:
      - target: ArkulatorWidgetExtension
      - package: RealmSwift

  ArkulatorTests:
    settings:
      TARGETED_DEVICE_FAMILY: 1
      SUPPORTS_MACCATALYST: false
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    platform: iOS
    type: bundle.unit-test
    dependencies:
      - target: Arkulator
      - package: RealmSwift
    sources:
      ArkulatorTests
    info:
      path: ArkulatorTests/Info.plist
  ArkulatorWidgetExtension:
    settings:
      TARGETED_DEVICE_FAMILY: 1
      SUPPORTS_MACCATALYST: false
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      PRODUCT_BUNDLE_IDENTIFIER: com.urielh.Arkulator.ArkulatorWidget
    platform: iOS
    type: app-extension
    subtype: widgetkit-extension
    sources:
      ArkulatorWidget
    dependencies:
      - package: RealmSwift
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
    info:
      path: ArkulatorWidget/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleDisplayName : "Arkulator"
        NSExtension:
          NSExtensionPointIdentifier: "com.apple.widgetkit-extension"
    entitlements:
      path: ArkulatorWidget/ArkulatorWidgetExtension.entitlements
      properties:
        com.apple.security.application-groups: [group.com.arkulator]
    
